config/routes.rb
Rails.application.routes.draw do
  resources :twilio_books
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root :to => "twilio_books#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/twilio_book.rb
class TwilioBook < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/twilio_books_controller.rb
class TwilioBooksController < ApplicationController
  before_action :set_twilio_book, only: [:show, :edit, :update, :destroy]

  # GET /twilio_books
  # GET /twilio_books.json
  def index
    @twilio_books = TwilioBook.all
  end

  # GET /twilio_books/1
  # GET /twilio_books/1.json
  def show
  end

  # GET /twilio_books/new
  def new
    @twilio_book = TwilioBook.new
  end

  # GET /twilio_books/1/edit
  def edit
  end

  # POST /twilio_books
  # POST /twilio_books.json
  def create
    @twilio_book = TwilioBook.new(twilio_book_params)

    respond_to do |format|
      if @twilio_book.save
        message = "The twilio message '#{@twilio_book.message_name}' was just added."
        TwilioTextMessenger.new(message).call
        format.html { redirect_to @twilio_book, notice: 'Twilio book was successfully created.' }
        format.json { render :show, status: :created, location: @twilio_book }
      else
        format.html { render :new }
        format.json { render json: @twilio_book.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /twilio_books/1
  # PATCH/PUT /twilio_books/1.json
  def update
    respond_to do |format|
      if @twilio_book.update(twilio_book_params)
        format.html { redirect_to @twilio_book, notice: 'Twilio book was successfully updated.' }
        format.json { render :show, status: :ok, location: @twilio_book }
      else
        format.html { render :edit }
        format.json { render json: @twilio_book.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /twilio_books/1
  # DELETE /twilio_books/1.json
  def destroy
    @twilio_book.destroy
    respond_to do |format|
      format.html { redirect_to twilio_books_url, notice: 'Twilio book was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_twilio_book
      @twilio_book = TwilioBook.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def twilio_book_params
      params.require(:twilio_book).permit(:message_name, :message_description)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/twilio_books_helper.rb
module TwilioBooksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Twilio</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/twilio_books/_form.html.erb
<%= form_with(model: twilio_book, local: true) do |form| %>
  <% if twilio_book.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(twilio_book.errors.count, "error") %> prohibited this twilio_book from being saved:</h2>

      <ul>
      <% twilio_book.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :message_name %>
    <%= form.text_field :message_name, id: :twilio_book_message_name %>
  </div>

  <div class="field">
    <%= form.label :message_description %>
    <%= form.text_area :message_description, id: :twilio_book_message_description %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/twilio_books/edit.html.erb
<h1>Editing Twilio Book</h1>

<%= render 'form', twilio_book: @twilio_book %>

<%= link_to 'Show', @twilio_book %> |
<%= link_to 'Back', twilio_books_path %>

app/views/twilio_books/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Twilio Books</h1>

<table>
  <thead>
    <tr>
      <th>Message name</th>
      <th>Message description</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @twilio_books.each do |twilio_book| %>
      <tr>
        <td><%= twilio_book.message_name %></td>
        <td><%= twilio_book.message_description %></td>
        <td><%= link_to 'Show', twilio_book %></td>
        <td><%= link_to 'Edit', edit_twilio_book_path(twilio_book) %></td>
        <td><%= link_to 'Destroy', twilio_book, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Twilio Book', new_twilio_book_path %>

app/views/twilio_books/new.html.erb
<h1>New Twilio Book</h1>

<%= render 'form', twilio_book: @twilio_book %>

<%= link_to 'Back', twilio_books_path %>

app/views/twilio_books/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Message name:</strong>
  <%= @twilio_book.message_name %>
</p>

<p>
  <strong>Message description:</strong>
  <%= @twilio_book.message_description %>
</p>

<%= link_to 'Edit', edit_twilio_book_path(@twilio_book) %> |
<%= link_to 'Back', twilio_books_path %>